### ISSUE TITLE
When awesome_video_player is added and you exit to the background, the GCDWebServer will freeze the IOS project

### ISSUE THREAD

**Issue by Sansuihe** [nateshmbhat/awesome_video_player#50]
My project uses the awesome_video_player and flutter_foreground_task plugins. Everything works fine without enabling flutter_foreground_task. When I started doing the front-end tasks, the Android end was also normal, but the IOS would cause the project to freeze, and the error message was triggered by the GCDWebServer. After investigation, it was found that awesome_video_player used GCDWebServer. How should I handle this? I don't need to use GCDWebServer when the APP is in the background.

**Comment by HudsonJunior** [comment]
I have the same issue

**Comment by HudsonJunior** [comment]
@Sansuihe I believe I fixed the issue [here](https://github.com/nateshmbhat/awesome_video_player/pull/51). Could you test?

**Comment by Sansuihe** [comment]
> [@Sansuihe](https://github.com/Sansuihe) I believe I fixed the issue [here](https://github.com/nateshmbhat/awesome_video_player/pull/51). Could you test?

@HudsonJunior How can I verify whether this issue has been fixed? Is there a new version or branch available for use in pub.dev?

**Comment by HudsonJunior** [comment]
@Sansuihe you can point directly to my forked repo for now.
https://github.com/HudsonJunior/awesome_video_player

**Comment by Sansuihe** [comment]
> [@Sansuihe](https://github.com/Sansuihe) you can point directly to my forked repo for now. https://github.com/HudsonJunior/awesome_video_player

@HudsonJunior The following error prompts will still appear。
 GCDWebServer                        0x0000000101cdc080 -[GCDWebServer _stop] + 516
1   awesome_video_player                0x0000000103412bf0 __31+[GCDWebServer(AsyncStop) load]_block_invoke_2 + 268
2   GCDWebServer                        0x0000000101cdc440 -[GCDWebServer _didEnterBackground:] + 208
3   CoreFoundation                      0x000000018a6a60e0 7821F73C-378B-3A10-BE90-EF526B7DBA93 + 86240
4   CoreFoundation                      0x000000018a6a9110 7821F73C-378B-3A10-BE90-EF526B7DBA93 + 98576
5   CoreFoundation                      0x000000018a6a9054 7821F73C-378B-3A10-BE90-EF526B7DBA93 + 98388
6   CoreFoundation                      0x000000018a6a6bac _CFXNotificationPost + 736
7   Foundation                          0x000000018931d7ac 34DE055D-8683-380A-9198-C3347211D13D + 75692
8   UIKitCore                           0x000000018e107a08 96636F64-106F-30C8-A780-82DCEBB0F443 + 18381320
9   UIKitCore                           0x000000018d194388 96636F64-106F-30C8-A780-82DCEBB0F443 + 2179976
10  UIKitCore                           0x000000018e1077e8 96636F64-106F-30C8-A780-82DCEBB0F443 + 18380776
11  UIKitCore                           0x000000018d0f0b5c 96636F64-106F-30C8-A780-82DCEBB0F443 + 1510236
12  UIKitCore                           0x000000018d0ec46c _UIScenePerformActionsWithLifecycleActionMask + 112
13  UIKitCore                           0x000000018d0f0870 96636F64-106F-30C8-A780-82DCEBB0F443 + 1509488
14  UIKitCore                           0x000000018d0f05e0 96636F64-106F-30C8-A780-82DCEBB0F443 + 1508832
15  UIKitCore                           0x000000018d0f02c8 96636F64-106F-30C8-A780-82DCEBB0F443 + 1508040
16  UIKitCore                           0x000000018d0eff30 96636F64-106F-30C8-A780-82DCEBB0F443 + 1507120
17  UIKitCore                           0x000000018d0eca5c 96636F64-106F-30C8-A780-82DCEBB0F443 + 1493596
18  UIKitCore                           0x000000018d0ed078 96636F64-106F-30C8-A780-82DCEBB0F443 + 1495160
19  UIKitCore                           0x000000018d0ec99c _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 224
20  UIKitCore                           0x000000018d0ec64c 96636F64-106F-30C8-A780-82DCEBB0F443 + 1492556
21  UIKitCore                           0x000000018d0ec224 96636F64-106F-30C8-A780-82DCEBB0F443 + 1491492
22  UIKitCore                           0x000000018d0ebb7c 96636F64-106F-30C8-A780-82DCEBB0F443 + 1489788
23  UIKitCore                           0x000000018d0eb9f4 96636F64-106F-30C8-A780-82DCEBB0F443 + 1489396
24  UIKitCore                           0x000000018d2443e0 96636F64-106F-30C8-A780-82DCEBB0F443 + 2900960
25  FrontBoardServices                  0x00000001a5099094 E5499075-AB01-3028-BCB5-3D19F26FF7ED + 147604
26  FrontBoardServices                  0x00000001a50946fc E5499075-AB01-3028-BCB5-3D19F26FF7ED + 128764
27  FrontBoardServices                  0x00000001a5098dc0 E5499075-AB01-3028-BCB5-3D19F26FF7ED + 146880
28  FrontBoardServices                  0x00000001a509bca0 E5499075-AB01-3028-BCB5-3D19F26FF7ED + 158880
29  FrontBoardServices                  0x00000001a5093d38 E5499075-AB01-3028-BCB5-3D19F26FF7ED + 126264
30  FrontBoardServices                  0x00000001a509bbcc E5499075-AB01-3028-BCB5-3D19F26FF7ED + 158668
31  FrontBoardServices                  0x00000001a509ba40 E5499075-AB01-3028-BCB5-3D19F26FF7ED + 158272
32  libdispatch.dylib                   0x000000010577a064 _dispatch_client_callout + 16
33  libdispatch.dylib                   0x00000001057647fc _dispatch_block_invoke_direct + 296
34  FrontBoardServices                  0x00000001a50938ac E5499075-AB01-3028-BCB5-3D19F26FF7ED + 125100
35  FrontBoardServices                  0x00000001a5093748 E5499075-AB01-3028-BCB5-3D19F26FF7ED + 124744
36  FrontBoardServices                  0x00000001a50937b0 E5499075-AB01-3028-BCB5-3D19F26FF7ED + 124848
37  CoreFoundation                      0x000000018a6a0a8c 7821F73C-378B-3A10-BE90-EF526B7DBA93 + 64140
38  CoreFoundation                      0x000000018a6a08a4 7821F73C-378B-3A10-BE90-EF526B7DBA93 + 63652
39  CoreFoundation                      0x000000018a6a0700 7821F73C-378B-3A10-BE90-EF526B7DBA93 + 63232
40  CoreFoundation                      0x000000018a6a1080 7821F73C-378B-3A10-BE90-EF526B7DBA93 + 65664
41  CoreFoundation                      0x000000018a6a2c3c CFRunLoopRunSpecific + 572
42  GraphicsServices                    0x00000001d7881454 GSEventRunModal + 168
43  UIKitCore                           0x000000018d0b5274 96636F64-106F-30C8-A780-82DCEBB0F443 + 1266292
44  UIKitCore                           0x000000018d080a28 UIApplicationMain + 336
45  UIKitCore                           0x000000018d162168 96636F64-106F-30C8-A780-82DCEBB0F443 + 1974632
46  Runner.debug.dylib                  0x0000000101d89e2c $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 120
47  Runner.debug.dylib                  0x0000000101d89da4 $s6Runner11AppDelegateC5$mainyyFZ + 44
48  Runner.debug.dylib                  0x0000000101d89ea8 __debug_main_executable_dylib_entry_point + 28
49  dyld                                0x00000001b1577f08 86D5253D-4FD1-36F3-B4AB-25982C90CBF4 + 257800

**Comment by HudsonJunior** [comment]
@Sansuihe the issue was fixed for me even with the log. I couldn't make the log disappear as the error comes from an underlying dependency; however, stopping the cache server before the underlying dependency did it, solved the issue apparently. The log is there, but it doesn't freeze the UI thread anymore.
